# -*- coding: utf-8 -*-
"""gzsDataControl

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k2Gf_M65wBGwlIvNtIOXR3IA3Un2SXCB
"""

from google.colab import drive
drive.mount("/content/drive")

percentageData = []
averageData=[]
titleList=[]

import os
import gzip
import numpy as np
for pathname, dirnames, filenames in os.walk("/content/drive/MyDrive/Colab Notebooks/IMPLICON"):
  for file in filenames:
    if(file[-3:] == ".gz"):
      # print(file)
      newData=[]
      with gzip.open("/content/drive/MyDrive/Colab Notebooks/IMPLICON/"+file, 'rt', 'utf-8') as gz:
        for line in gz:
          if(line.split("\t")[0] == "12" and int(line.split("\t")[1]) > 109528252 and int(line.split("\t")[2]) < 109528472):
            newData.append(float(line.split("\t")[3]))
      if(np.average(newData) > -1):
        print(file,np.average(newData))
      averageData.append(np.average(newData))
      percentageData.append(np.array(newData))
      # titleList.append(file.split(".")[0])

print(averageData)

import matplotlib.pyplot as plt
 
# ヒストグラムを出力
plt.hist(averageData,bins=20)
# 箱ひげ図を出力
fig, ax = plt.subplots()


bp = ax.boxplot(percentageData,widths=1) # 複数指定する場合はタプル型で渡します。
# ax.set_xticklabels(titleList)

plt.title('Dlk1')

from google.colab import drive
drive.mount("/content/drive")

percentageData = []
averageData=[]
titleList=[]
newPlaceData=[]
placeData=[]

import os
import gzip
import numpy as np
for pathname, dirnames, filenames in os.walk("/content/drive/MyDrive/Colab Notebooks/IMPLICON"):
  for file in filenames:
    if(file[-12:] == "heart.cov.gz"):
      # print(file)
      newData=[]
      newPlaceData=[]
      with gzip.open("/content/drive/MyDrive/Colab Notebooks/IMPLICON/"+file, 'rt', 'utf-8') as gz:
        for line in gz:
          if(line.strip().split("\t")[0] == "12" and int(line.strip().split("\t")[1]) > 109528252 and int(line.strip().split("\t")[2]) < 109528472):
            newData.append(float(line.split("\t")[3]))
            newPlaceData.append(int(line.strip().split("\t")[1]))
            print(file,line.strip().split("\t")[1],line.strip().split("\t")[2])
      # if(np.average(newData) > -1):
        
      averageData.append(np.average(newData))
      percentageData.append(np.array(newData))
      titleList.append(file.split(".")[0][11:])
      placeData.append(newPlaceData)

print(percentageData)
print(len(percentageData[0]),len(percentageData[1]),len(percentageData[2]))
for i in np.arange(23):
  print(placeData[0][i],placeData[1][i],placeData[2][i])

import matplotlib.pyplot as plt
 
# ヒストグラムを出力
# plt.hist(averageData,bins=20)
# 箱ひげ図を出力
fig, ax = plt.subplots()


bp = ax.boxplot(percentageData) # 複数指定する場合はタプル型で渡します。
ax.set_xticklabels(titleList)
ax.set_ylim(0,100)

plt.title('Dlk1')

